[build]
  publish = "app/"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
 for = "/*"
 [headers.values]
  cache-control = '''
  no-store, 
  no-cache, 
  max-age=0, 
  must-revalidate, 
  proxy-revalidate'''